name: SIT Flow
on:
  pull_request_review:
    types: [submitted]
jobs:
  lint:
    if: |
      github.event.review.state == 'approved' &&
      github.event.pull_request.base.ref == 'sit'
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: echo "Linter done"
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Build code
        run: echo "Building code"
  schema_validator:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Schema validator
        run: echo "validating schema"
  deploy:
    needs: schema_validator
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: echo "Deploying"
  merge:
    needs: deploy
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{toJSON(github.event.pull_request.number)}}
          method: squash
  create_main_pull_request:
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/actions/create-pr/action.js')
            console.log(script({github, context}))
