name: Events Demo 1
on:
  pull_request_review:
    types: [submitted]
    branches:
      - main
  # pull_request:
  #   types: [opened, edited, closed]
  #   branches:
  #     - main
  #     - "dev-*" # dev-new dev-this-is-new
  #     - "feature/**" # feature/new feature/new/button
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - "dev-*" # dev-new dev-this-is-new
  #     - "feature/**" # feature/new feature/new/button
  #   paths-ignore:
  #     - ".github/workflows/*"
jobs:
  deploy:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Deploy project
        run: echo "Deploying..."
  merge_pull_request:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 7
          method: merge
